# Generated by Django 4.1 on 2022-08-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=20)),
                ('str_field', models.TextField(blank=True, null=True)),
                ('int_field', models.ImageField(blank=True, max_length=10, null=True, upload_to='')),
                ('date_field', models.DateTimeField(blank=True, null=True)),
                ('email_field', models.EmailField(blank=True, max_length=254, null=True)),
                ('document', models.FileField(upload_to='documents/')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
