# Generated by Django 4.1 on 2022-08-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0003_createform_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createform',
            name='User',
        ),
    ]
