# Generated by Django 4.1 on 2022-09-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0004_remove_createform_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='createform',
            name='author',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
