# Generated by Django 4.1 on 2022-09-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0006_rename_form_name_createform_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createform',
            name='author',
        ),
    ]
