# Generated by Django 4.1 on 2022-09-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0007_remove_createform_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='createform',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='createform',
            name='privacy',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
