# Generated by Django 4.1 on 2022-09-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0008_createform_author_createform_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='createform',
            name='form_array',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
