# Generated by Django 4.1 on 2022-09-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0009_createform_form_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createform',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='createform',
            name='Check_Box',
        ),
        migrations.RemoveField(
            model_name='createform',
            name='Currency',
        ),
        migrations.RemoveField(
            model_name='createform',
            name='Currency_currency',
        ),
        migrations.RemoveField(
            model_name='createform',
            name='Number',
        ),
        migrations.RemoveField(
            model_name='createform',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='createform',
            name='Phone_number',
        ),
        migrations.RemoveField(
            model_name='createform',
            name='Text_field',
        ),
        migrations.RemoveField(
            model_name='createform',
            name='Textarea',
        ),
        migrations.RemoveField(
            model_name='createform',
            name='Url',
        ),
        migrations.RemoveField(
            model_name='createform',
            name='document',
        ),
        migrations.RemoveField(
            model_name='createform',
            name='email_field',
        ),
        migrations.RemoveField(
            model_name='createform',
            name='form_array',
        ),
    ]
