# Generated by Django 4.1 on 2022-09-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0010_remove_createform_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createform',
            name='upload_at',
        ),
        migrations.AddField(
            model_name='createform',
            name='form_array',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
