# Generated by Django 4.1 on 2022-09-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0011_remove_createform_upload_at_createform_form_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createform',
            name='name',
        ),
        migrations.RemoveField(
            model_name='createform',
            name='privacy',
        ),
    ]
