# Generated by Django 4.1 on 2022-09-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0012_remove_createform_name_remove_createform_privacy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createform',
            old_name='form_array',
            new_name='formarray',
        ),
    ]
