# Generated by Django 4.1 on 2022-09-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0013_rename_form_array_createform_formarray'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createform',
            name='formarray',
            field=models.Field(blank=True, max_length=1000, null=True),
        ),
    ]
