# Generated by Django 4.1 on 2022-09-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0015_alter_createform_formarray'),
    ]

    operations = [
        migrations.AddField(
            model_name='createform',
            name='kone_sefid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='createform',
            name='formarray',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
