# Generated by Django 4.1 on 2022-09-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0016_createform_kone_sefid_alter_createform_formarray'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createform',
            name='kone_sefid',
        ),
    ]
