# Generated by Django 4.1 on 2022-09-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0018_alter_createform_formarray'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createform',
            name='formarray',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
